---
# Express API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
      - name: express-api
        image: your-express-api-image
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: sqlserver.example.com
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: DB_NAME
          value: your_database

---
# Express API Service
apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  selector:
    app: express-api
  ports:
  - port: 5000
    targetPort: 5000

---
# React Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: your-react-client-image
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://express-api:5000

---
# React Client Service
apiVersion: v1
kind: Service
metadata:
  name: react-client
spec:
  selector:
    app: react-client
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

---
# Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-user: your_username_base64
  db-password: your_password_base64